"""Security platform types (Sprint 65D)."""

from __future__ import annotations

FINDING_STATUSES = (
    "OPEN", "ACKNOWLEDGED", "ACCEPTED_RISK", "IN_REMEDIATION",
    "RESOLVED", "FALSE_POSITIVE", "EXPIRED",
)

FINDING_SEVERITIES = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")

FINDING_SOURCES = (
    "SOURCE_CODE", "DEPENDENCY", "CONTAINER", "KUBERNETES", "CLOUD",
    "IAC", "SECRET", "IAM", "RUNTIME", "SBOM", "LICENSE",
)

SCAN_KINDS = (
    "SAST", "DEPENDENCY", "SECRET", "CONTAINER", "SBOM", "KUBERNETES",
    "CLOUD", "IAC", "IAM", "LICENSE",
)

REMEDIATION_KINDS = (
    "PATCH_IMAGE", "UPGRADE_DEPENDENCY", "ROTATE_KEY", "REVOKE_API_KEY",
    "DISABLE_ACCOUNT", "RESTRICT_IAM", "ADD_NETWORK_POLICY", "ENFORCE_ENCRYPTION",
    "FIX_TERRAFORM", "ROLLBACK_DEPLOYMENT", "CREATE_INCIDENT", "NOTIFY_OWNER",
)
