"""Sprint 52C — Industry templates for the Demo Organization Generator.

Each template is a pure-data definition (no secrets, no real infrastructure)
used by :class:`app.services.demo_organization.DemoOrganizationService` to seed
a realistic, self-contained demo organization.

Schema of a template:
    name, industry, summary, highlights[list[str]]
    clusters[list[str]], util(float 0-1), monthly_spend(float), waste_pct(float)
    services: [{name, tier(1-3), team, availability?, latency_ms?, description?}]
    deps: [(source_name, target_name, dependency_type)]
    incidents: [{title, service, severity, ...optional flavor...}]

Optional incident flavor keys consumed by the seeder: summary, root_cause,
trigger, resolution, alert_name, alert_desc, provider, change_provider, actor,
version, confidence, days_ago, hours, duration_min, occurrences, status
("COMPLETED"|"RUNNING"), war_room(bool), postmortem(bool), remediation(bool),
steps[list[(provider, action)]], recs[list[(type, title, risk, conf, mins)]].
"""

from __future__ import annotations

DEMO_TEMPLATES: dict[str, dict] = {
    # ------------------------------------------------------------------ #
    "ecommerce": {
        "name": "ShopFlow (E-Commerce Demo)",
        "industry": "E-Commerce",
        "summary": "A high-traffic online retail platform with checkout, payments, and search.",
        "highlights": [
            "Black-Friday-scale traffic & capacity forecasts",
            "Checkout regression incident with war room & postmortem",
            "Payment + cart + inventory dependency graph",
        ],
        "clusters": ["prod-us-east", "prod-eu-west"],
        "util": 0.62,
        "monthly_spend": 54000,
        "waste_pct": 0.24,
        "services": [
            {"name": "web-storefront", "tier": 1, "team": "Frontend", "availability": 99.95, "latency_ms": 250},
            {"name": "checkout-service", "tier": 1, "team": "Payments", "availability": 99.99, "latency_ms": 200},
            {"name": "payment-gateway", "tier": 1, "team": "Payments", "availability": 99.99, "latency_ms": 180},
            {"name": "cart-service", "tier": 2, "team": "Orders", "availability": 99.9, "latency_ms": 150},
            {"name": "catalog-search", "tier": 2, "team": "Search", "availability": 99.5, "latency_ms": 300},
            {"name": "inventory-service", "tier": 2, "team": "Orders", "availability": 99.9, "latency_ms": 220},
            {"name": "orders-db", "tier": 1, "team": "Data", "availability": 99.99, "latency_ms": 60},
        ],
        "deps": [
            ("web-storefront", "checkout-service", "SYNC"),
            ("web-storefront", "catalog-search", "SYNC"),
            ("web-storefront", "cart-service", "SYNC"),
            ("checkout-service", "payment-gateway", "SYNC"),
            ("checkout-service", "inventory-service", "SYNC"),
            ("checkout-service", "orders-db", "DATASTORE"),
            ("cart-service", "orders-db", "DATASTORE"),
            ("inventory-service", "orders-db", "DATASTORE"),
        ],
        "incidents": [
            {
                "title": "Checkout 5xx spike after release",
                "service": "checkout-service",
                "severity": "CRITICAL",
                "alert_name": "checkout-service HTTP 5xx > 5%",
                "summary": "A bad config in v2.3.0 caused checkout to reject ~12% of orders.",
                "root_cause": "v2.3.0 introduced a null payment-token path that 500'd on guest checkout.",
                "trigger": "Deploy checkout-service v2.3.0 (PR #1842)",
                "resolution": "Rolled back to v2.2.9; guest checkout recovered within 6 minutes.",
                "version": "v2.3.0",
                "confidence": 93,
                "days_ago": 2,
                "duration_min": 38,
                "war_room": True,
                "postmortem": True,
            },
            {
                "title": "Catalog search latency degradation",
                "service": "catalog-search",
                "severity": "HIGH",
                "alert_name": "catalog-search p95 > 800ms",
                "summary": "Search p95 latency tripled during a traffic surge.",
                "root_cause": "Index shard hot-spotting under load; missing autoscaling on search pods.",
                "trigger": "Marketing campaign traffic spike",
                "resolution": "Scaled search replicas and rebalanced shards.",
                "confidence": 84,
                "days_ago": 5,
                "duration_min": 70,
            },
            {
                "title": "Inventory sync drift (investigating)",
                "service": "inventory-service",
                "severity": "WARNING",
                "alert_name": "inventory-service stale-read warning",
                "trigger": "Replication lag on orders-db replica",
                "status": "RUNNING",
                "days_ago": 0,
                "war_room": False,
                "postmortem": False,
            },
        ],
    },
    # ------------------------------------------------------------------ #
    "fintech": {
        "name": "LedgerPay (FinTech Demo)",
        "industry": "FinTech",
        "summary": "A payments & ledger platform with strict latency and availability SLOs.",
        "highlights": [
            "PCI-style high-tier services & 99.99% SLOs",
            "Ledger reconciliation incident with remediation approval",
            "Fraud-detection + transaction dependency graph",
        ],
        "clusters": ["prod-fin-1", "prod-fin-2"],
        "util": 0.58,
        "monthly_spend": 72000,
        "waste_pct": 0.18,
        "services": [
            {"name": "transaction-api", "tier": 1, "team": "Payments", "availability": 99.99, "latency_ms": 120},
            {"name": "ledger-service", "tier": 1, "team": "Ledger", "availability": 99.999, "latency_ms": 90},
            {"name": "fraud-detection", "tier": 1, "team": "Risk", "availability": 99.95, "latency_ms": 150},
            {"name": "auth-service", "tier": 1, "team": "Identity", "availability": 99.99, "latency_ms": 100},
            {"name": "settlement-batch", "tier": 2, "team": "Ledger", "availability": 99.5, "latency_ms": 400},
            {"name": "notifications", "tier": 3, "team": "Platform", "availability": 99.0, "latency_ms": 500},
            {"name": "ledger-db", "tier": 1, "team": "Data", "availability": 99.999, "latency_ms": 40},
        ],
        "deps": [
            ("transaction-api", "auth-service", "SYNC"),
            ("transaction-api", "fraud-detection", "SYNC"),
            ("transaction-api", "ledger-service", "SYNC"),
            ("ledger-service", "ledger-db", "DATASTORE"),
            ("settlement-batch", "ledger-db", "DATASTORE"),
            ("transaction-api", "notifications", "ASYNC"),
            ("fraud-detection", "ledger-db", "DATASTORE"),
        ],
        "incidents": [
            {
                "title": "Ledger reconciliation mismatch",
                "service": "ledger-service",
                "severity": "CRITICAL",
                "alert_name": "ledger-service reconciliation error",
                "summary": "Settlement batch double-counted ~0.3% of transactions.",
                "root_cause": "A race in settlement-batch retried committed entries after a timeout.",
                "trigger": "Deploy settlement-batch v4.1.0",
                "resolution": "Paused batch, replayed from checkpoint, patched idempotency key.",
                "version": "v4.1.0",
                "change_provider": "GITHUB",
                "confidence": 91,
                "days_ago": 3,
                "duration_min": 95,
                "war_room": True,
                "postmortem": True,
            },
            {
                "title": "Auth latency breach",
                "service": "auth-service",
                "severity": "HIGH",
                "alert_name": "auth-service p99 > 300ms",
                "summary": "Token validation latency breached the 99.99% SLO for 22 minutes.",
                "root_cause": "Connection pool exhaustion against ledger-db during a traffic spike.",
                "trigger": "Connection pool misconfiguration",
                "resolution": "Increased pool size and added circuit breaker.",
                "confidence": 86,
                "days_ago": 6,
                "duration_min": 22,
            },
            {
                "title": "Fraud model elevated false positives (investigating)",
                "service": "fraud-detection",
                "severity": "WARNING",
                "alert_name": "fraud-detection FP rate warning",
                "trigger": "New model weights deployed",
                "status": "RUNNING",
                "days_ago": 0,
            },
        ],
    },
    # ------------------------------------------------------------------ #
    "healthcare": {
        "name": "CareGrid (Healthcare Demo)",
        "industry": "Healthcare",
        "summary": "A patient records & scheduling platform with compliance-grade reliability.",
        "highlights": [
            "EHR + scheduling + messaging services",
            "Records availability incident with postmortem",
            "Compliance-aware dependency graph & SLOs",
        ],
        "clusters": ["prod-health-1"],
        "util": 0.5,
        "monthly_spend": 41000,
        "waste_pct": 0.2,
        "services": [
            {"name": "patient-records", "tier": 1, "team": "EHR", "availability": 99.99, "latency_ms": 200},
            {"name": "scheduling-service", "tier": 1, "team": "Scheduling", "availability": 99.95, "latency_ms": 250},
            {"name": "provider-portal", "tier": 2, "team": "Web", "availability": 99.9, "latency_ms": 300},
            {"name": "messaging-service", "tier": 2, "team": "Comms", "availability": 99.5, "latency_ms": 350},
            {"name": "billing-service", "tier": 2, "team": "Billing", "availability": 99.9, "latency_ms": 280},
            {"name": "records-db", "tier": 1, "team": "Data", "availability": 99.99, "latency_ms": 50},
        ],
        "deps": [
            ("provider-portal", "patient-records", "SYNC"),
            ("provider-portal", "scheduling-service", "SYNC"),
            ("scheduling-service", "messaging-service", "ASYNC"),
            ("patient-records", "records-db", "DATASTORE"),
            ("scheduling-service", "records-db", "DATASTORE"),
            ("billing-service", "records-db", "DATASTORE"),
        ],
        "incidents": [
            {
                "title": "Patient records read errors",
                "service": "patient-records",
                "severity": "CRITICAL",
                "alert_name": "patient-records availability < 99.9%",
                "summary": "Providers saw intermittent record-load failures for 28 minutes.",
                "root_cause": "records-db failover left stale connections in the records service pool.",
                "trigger": "Database failover event",
                "change_provider": "AWS",
                "resolution": "Recycled connection pools and pinned to the new primary.",
                "confidence": 89,
                "days_ago": 4,
                "duration_min": 28,
                "war_room": True,
                "postmortem": True,
            },
            {
                "title": "Scheduling slowdowns at peak",
                "service": "scheduling-service",
                "severity": "HIGH",
                "alert_name": "scheduling-service p95 > 700ms",
                "summary": "Appointment booking slowed during morning peak.",
                "root_cause": "Under-provisioned scheduling pods; no HPA configured.",
                "trigger": "Morning booking surge",
                "resolution": "Enabled autoscaling and right-sized requests.",
                "confidence": 82,
                "days_ago": 7,
                "duration_min": 55,
            },
        ],
    },
    # ------------------------------------------------------------------ #
    "saas": {
        "name": "TaskNova (SaaS Demo)",
        "industry": "B2B SaaS",
        "summary": "A multi-tenant productivity SaaS with API, web app, and background jobs.",
        "highlights": [
            "Multi-tenant API + web + workers",
            "Noisy-neighbor incident with remediation",
            "Cost optimization across idle dev/staging",
        ],
        "clusters": ["prod-saas-1", "staging"],
        "util": 0.48,
        "monthly_spend": 38000,
        "waste_pct": 0.3,
        "services": [
            {"name": "api-gateway", "tier": 1, "team": "Platform", "availability": 99.95, "latency_ms": 180},
            {"name": "app-web", "tier": 2, "team": "Frontend", "availability": 99.9, "latency_ms": 300},
            {"name": "tenant-service", "tier": 1, "team": "Core", "availability": 99.95, "latency_ms": 150},
            {"name": "billing-worker", "tier": 2, "team": "Billing", "availability": 99.5, "latency_ms": 600},
            {"name": "search-indexer", "tier": 3, "team": "Search", "availability": 99.0, "latency_ms": 800},
            {"name": "app-db", "tier": 1, "team": "Data", "availability": 99.99, "latency_ms": 55},
        ],
        "deps": [
            ("app-web", "api-gateway", "SYNC"),
            ("api-gateway", "tenant-service", "SYNC"),
            ("tenant-service", "app-db", "DATASTORE"),
            ("billing-worker", "app-db", "DATASTORE"),
            ("search-indexer", "app-db", "DATASTORE"),
            ("api-gateway", "search-indexer", "ASYNC"),
        ],
        "incidents": [
            {
                "title": "Noisy-neighbor tenant degrades API",
                "service": "api-gateway",
                "severity": "HIGH",
                "alert_name": "api-gateway p95 > 600ms",
                "summary": "One tenant's bulk import saturated shared API capacity.",
                "root_cause": "Missing per-tenant rate limits allowed an import to monopolize workers.",
                "trigger": "Tenant bulk-import job",
                "resolution": "Added per-tenant rate limiting and a bulk-job queue.",
                "confidence": 87,
                "days_ago": 3,
                "duration_min": 40,
                "war_room": True,
                "postmortem": True,
            },
            {
                "title": "Billing worker backlog",
                "service": "billing-worker",
                "severity": "WARNING",
                "alert_name": "billing-worker queue depth high",
                "summary": "Invoicing jobs backed up overnight.",
                "root_cause": "A slow third-party call serialized the worker.",
                "trigger": "Upstream provider slowdown",
                "resolution": "Parallelized workers and added a timeout/retry budget.",
                "confidence": 80,
                "days_ago": 8,
                "duration_min": 120,
            },
        ],
    },
    # ------------------------------------------------------------------ #
    "microservices": {
        "name": "MeshWorks (Microservices Demo)",
        "industry": "Microservices Platform",
        "summary": "A large microservices mesh showcasing blast-radius and dependency intelligence.",
        "highlights": [
            "10+ services with a deep dependency graph",
            "Cascading failure incident across the mesh",
            "Blast-radius analysis & deployment safety history",
        ],
        "clusters": ["prod-mesh-a", "prod-mesh-b"],
        "util": 0.6,
        "monthly_spend": 63000,
        "waste_pct": 0.26,
        "services": [
            {"name": "edge-gateway", "tier": 1, "team": "Edge", "availability": 99.95, "latency_ms": 120},
            {"name": "user-service", "tier": 1, "team": "Identity", "availability": 99.95, "latency_ms": 140},
            {"name": "order-service", "tier": 1, "team": "Orders", "availability": 99.9, "latency_ms": 160},
            {"name": "pricing-service", "tier": 2, "team": "Pricing", "availability": 99.9, "latency_ms": 130},
            {"name": "notification-service", "tier": 3, "team": "Comms", "availability": 99.0, "latency_ms": 400},
            {"name": "recommendation-service", "tier": 3, "team": "ML", "availability": 99.0, "latency_ms": 500},
            {"name": "cache-cluster", "tier": 2, "team": "Platform", "availability": 99.9, "latency_ms": 20},
            {"name": "primary-db", "tier": 1, "team": "Data", "availability": 99.99, "latency_ms": 45},
        ],
        "deps": [
            ("edge-gateway", "user-service", "SYNC"),
            ("edge-gateway", "order-service", "SYNC"),
            ("order-service", "pricing-service", "SYNC"),
            ("order-service", "recommendation-service", "ASYNC"),
            ("order-service", "notification-service", "ASYNC"),
            ("user-service", "cache-cluster", "DATASTORE"),
            ("pricing-service", "cache-cluster", "DATASTORE"),
            ("user-service", "primary-db", "DATASTORE"),
            ("order-service", "primary-db", "DATASTORE"),
            ("pricing-service", "primary-db", "DATASTORE"),
        ],
        "incidents": [
            {
                "title": "Cascading failure from cache outage",
                "service": "cache-cluster",
                "severity": "CRITICAL",
                "alert_name": "cache-cluster unavailable",
                "summary": "A cache node loss cascaded into user-service and pricing-service timeouts.",
                "root_cause": "Cache eviction storm overloaded primary-db, tripping downstream timeouts.",
                "trigger": "Cache node eviction + missing circuit breakers",
                "resolution": "Failed cache traffic over, added circuit breakers and read replicas.",
                "change_provider": "KUBERNETES",
                "confidence": 90,
                "days_ago": 2,
                "duration_min": 65,
                "war_room": True,
                "postmortem": True,
                "recs": [
                    ("Infrastructure", "Add circuit breakers on user-service and pricing-service", "MEDIUM", 91, 20),
                    ("Application", "Enable cache fallback to read replica", "MEDIUM", 84, 25),
                    ("Monitoring", "Add cascading-failure detection on the mesh", "LOW", 75, 15),
                ],
            },
            {
                "title": "Pricing-service deploy regression",
                "service": "pricing-service",
                "severity": "HIGH",
                "alert_name": "pricing-service error-rate > 3%",
                "summary": "A pricing rule change returned errors for some SKUs.",
                "root_cause": "Edge case in the new pricing rule engine for bundle SKUs.",
                "trigger": "Deploy pricing-service v3.2.1",
                "version": "v3.2.1",
                "resolution": "Rolled back and added contract tests for bundle pricing.",
                "confidence": 88,
                "days_ago": 6,
                "duration_min": 33,
            },
            {
                "title": "Recommendation latency spike (investigating)",
                "service": "recommendation-service",
                "severity": "WARNING",
                "alert_name": "recommendation-service p95 high",
                "trigger": "Model server cold starts",
                "status": "RUNNING",
                "days_ago": 0,
            },
        ],
    },
}
