"""Incident response platform types (Sprint 65C)."""

from __future__ import annotations

ESCALATION_CHANNELS = (
    "email", "sms", "voice", "slack", "teams", "discord", "webhook",
)

ROTATION_KINDS = ("PRIMARY", "SECONDARY", "FOLLOW_THE_SUN")

LIFECYCLE_DISPLAY = (
    "OPEN", "ACKNOWLEDGED", "INVESTIGATING", "MITIGATED", "MONITORING",
    "RESOLVED", "CLOSED", "POSTMORTEM_PENDING", "POSTMORTEM_COMPLETED",
)

MAJOR_INCIDENT_ROLES = (
    "COMMANDER", "COMMUNICATIONS_LEAD", "OPERATIONS_LEAD", "TIMELINE_RECORDER",
)

COMMUNICATION_KINDS = (
    "INTERNAL", "CUSTOMER", "EXECUTIVE", "ENGINEERING",
)

STATUS_COMPONENT_STATES = ("OPERATIONAL", "DEGRADED", "PARTIAL_OUTAGE", "MAJOR_OUTAGE", "MAINTENANCE")
